# Generated by Django 3.0.6 on 2020-05-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20200523_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applications',
                to='vacancies.Vacancy'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_cover_letter',
            field=models.CharField(max_length=500),
        ),
    ]
