# Generated by Django 3.0.6 on 2020-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_auto_20200528_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='company_images'),
        ),
    ]
